# Generated by Django 4.2.6 on 2023-11-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthReg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
