# Generated by Django 4.2.6 on 2023-12-05 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('workers', models.IntegerField(unique=True)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=255)),
                ('budget', models.FloatField()),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designer', models.IntegerField()),
                ('Builders', models.IntegerField()),
                ('Arcitectors', models.IntegerField()),
                ('Electrications', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=255)),
                ('materials', models.CharField(max_length=255, unique=True)),
                ('tech', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('ur_lico', models.BooleanField(default=False)),
                ('work_type', models.CharField(max_length=255)),
                ('User_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=255)),
                ('Geo_info', models.CharField(max_length=255)),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebDes.customers')),
                ('Given_workers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebDes.contractor', to_field='workers')),
                ('My_workers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebDes.employees')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials_article_set', to='WebDes.provider', to_field='materials')),
                ('obur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obur_article_set', to='WebDes.provider', to_field='tech')),
            ],
        ),
    ]
