# Generated by Django 4.2.6 on 2023-12-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDes', '0003_main_tovar'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='Commentary',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
