# Generated by Django 4.2.6 on 2023-12-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDes', '0004_zayavka_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
