# Generated by Django 4.2.6 on 2023-12-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDes', '0005_zayavka_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='Deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='Deleted_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
