# Generated by Django 4.2.6 on 2023-12-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDes', '0006_zayavka_deleted_zayavka_deleted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_tovar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
