# Generated by Django 4.2.6 on 2023-12-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebDes', '0007_alter_main_tovar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
